services:
  todoapi:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "${ASPNETCORE_HTTP_PORTS:-8080}"
      ASPNETCORE_HTTPS_PORTS: "${ASPNETCORE_HTTPS_PORTS:-8081}"
    ports:
      - "${ASPNETCORE_HTTP_PORTS:-8080}:8080"
      - "${ASPNETCORE_HTTPS_PORTS:-8081}:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro